services:
  postgres:
    container_name: database
    hostname: postgres_database
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - backend/.env

  backend:
    links:
      - "postgres:postgres"
    container_name: backend-app
    restart: always
    build: backend
    env_file:
      - backend/.env
    ports:
      - 5000:5000

  adminer:
    links:
      - "postgres:postgres"
    container_name: adminer
    image: adminer
    restart: always
    environment:
      host: localhost
    ports:
      - 8080:8080

volumes:
  postgres-data: