services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongodb_password
    secrets:
      - mongodb_user
      - mongodb_password
    

secrets:
  mongodb_user:
    file: ./secrets/mongodb_user
  mongodb_password:
    file: ./secrets/mongodb_password
  