services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
    secrets:
      - mongodb_user
      - mongodb_password
    volumes:
      - mongo-data:/data/db

secrets:
  mongodb_user:
    file: ./secrets/mongodb_user
  mongodb_password:
    file: ./secrets/mongodb_password

volumes:
  mongo-data:
