services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    links:
      - "postgres:postgres"
    container_name: backend-app
    restart: always
    build: ./
    env_file:
      - ./.env
    ports:
      - 8000:5000

  adminer:
    links:
      - "postgres:postgres"
    container_name: adminer
    image: adminer
    restart: always
    environment:
      host: localhost
    ports:
      - 8080:8080

volumes:
  postgres-data: