"""Add Contract Models

Revision ID: 76acca4254f5
Revises: 429fbe7b6da4
Create Date: 2024-09-12 20:06:38.696186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76acca4254f5"
down_revision: Union[str, None] = "429fbe7b6da4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("contractor_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_contracts_chat_id_chats")
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["users.id"],
            name=op.f("fk_contracts_contractor_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["users.id"], name=op.f("fk_contracts_customer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
    )
    op.create_unique_constraint(op.f("uq_profiles_user_id"), "profiles", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_profiles_user_id"), "profiles", type_="unique")
    op.drop_table("contracts")
    # ### end Alembic commands ###
